config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "logins#new"
  resources 'logins'
  resources 'users'
  post '/add_members' => 'users#add_members'
  delete '/remove_group_member' => 'channels#remove_group_member'
  resources 'channels' do
    resources 'messages'
  end

  get '/not_found' => 'errors#not_found'
end

app/models/channel.rb
# frozen_string_literal: true

# Channel model
class Channel < ApplicationRecord
  attr_accessor :member_id, :add_member, :remove_member

  has_many :messages, dependent: :destroy
  has_many :broadcasts, dependent: :destroy

  validates :channel_name, presence: true, uniqueness: true
  scope :public_channels, -> { where(is_private: false) }
  after_update_commit :broadcast_channel

  private


  def broadcast_channel
    return if is_private

    if add_member || remove_member
      user = User.find_by_id(member_id)
      if user.present?
        personal_channel = Channel.find_by(channel_name: user.username)&.id
        personal_channel = Channel.create(channel_name: user.username, is_private: true, member_ids: [user.id], creator_id: [user.id], last_read: {user.id.to_s=> Time.now}, room_presence: {user.id.to_s=> Time.now})&.id unless personal_channel.present?
        broadcast_append_to "add_remove_channels_#{member_id}", partial: 'partials/add_remove_channel', locals: { remove: 'true', channel_id: id, personal_channel: }
      end
      member_ids.each do |member|
        broadcast_append_to "add_remove_channels_#{member}", partial: 'partials/add_remove_channel', locals: { remove: 'false', channel_id: id, personal_channel: '' }
      end
    end
    update_attr_accessor
  end

  def update_attr_accessor
    self.add_member = false
    self.remove_member = false
    self.member_id = nil
  end
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

# Channels controller
class ChannelsController < ApplicationController
  before_action :find_current_user
  before_action :display_channels, only: %i[show index]
  before_action :show_users, only: %i[show index]

  def create
    if params[:is_private]
      if params[:selected_user].present?
        create_private_channel
      else
        create_personal_channel
      end
    else
      create_group_chat
    end
  end

  def index
    redirect_to root_path unless current_user
  end

  def new
    @channels = Channel.new
  end

  def remove_group_member
    channel = Channel.find_by_id(params[:channel_id])
    channel.member_ids.delete(params[:member_id].to_i)
    channel.last_read.delete(params[:member_id].to_s)
    channel.room_presence.delete(params[:member_id].to_s)
    channel.member_id = params[:member_id].to_i
    channel.remove_member = true
    channel.save
  end

  def show
    @single_room = Channel.find_by_id(params[:id])
    if @single_room.present? && @single_room.member_ids.include?(@current_user.id)
      update_last_read
      @message = Message.new
      @messages = @single_room.messages.order(:created_at).group_by { |m| m.created_at.to_date }      
      render 'index'
    else
      redirect_to not_found_path
    end
  end

  private

  def create_group_chat
    @channels = Channel.create(create_params(params['channel_name']))
    redirect_to channel_path(@channels.id) if @channels.save
  end

  def create_params(name, is_pvt: false)
    {
      channel_name: name,
      member_ids: [session[:user_id]],
      creator_id: session[:user_id],
      is_private: is_pvt,
    }
  end

  def create_personal_channel
    @channels = Channel.find_by(channel_name: @current_user.username)
    @channels = Channel.create(create_params(@current_user.username, is_pvt: true)) unless @channels.present?
    redirect_to channel_path(@channels.id)
  end

  def create_private_channel
    @channels = Channel.find_by(channel_name: get_channel_name(@current_user&.username, params[:selected_user][0]))
    @channels = Channel.create(create_private_channel_params) unless @channels.present?
    redirect_to channel_path(@channels.id)
  end

  def create_private_channel_params
    {
      channel_name: get_channel_name(@current_user&.username, params[:selected_user][0]),
      is_private: true,
      member_ids: [session[:user_id], find_user],
      last_read: { session[:user_id].to_s => Time.now, find_user.to_s => Time.now },
      room_presence: { @current_user.id.to_s => true, find_user.to_s => false }
    }
  end

  def display_channels
    @channels = Channel.public_channels&.where('? = ANY(member_ids)', @current_user&.id)
    @direct_messages = Channel.where('? = ANY(member_ids) AND ? = is_private', @current_user&.id, true)
  end

  def find_current_user
    @current_user = current_user
  end

  def find_user
    User.find_by_username(params[:selected_user]).id
  end

  def get_channel_name(user1, user2)
    [user2, user1].sort.join(',')
  end

  def show_users
    @users = User.all_except(@current_user)
  end

  def update_last_read

    update_room_presence

    last_read = @single_room.last_read
    @single_room.last_read[@current_user.id.to_s] = Time.now
    @single_room.save
  end

  def update_room_presence
    current_user_channel_ids = Channel.pluck(:id, :member_ids).select { |array| array[1].include?(@current_user.id) }.map { |array| array[0] }
    current_user_channels = Channel.where(id: current_user_channel_ids)
    current_user_channels.each do |channel|
      room_presence = channel.room_presence
      if channel == @single_room
        channel.room_presence[@current_user.id.to_s] = true
      else
        channel.last_read[@current_user.id.to_s] = Time.now if channel.room_presence[@current_user.id.to_s] == true
        channel.room_presence[@current_user.id.to_s] = false
      end
      channel.save
    end
  end
end

app/views/channels/_channel.html.erb
<%if channel.present?%>
  <div class="row filterDiscussions all read single">
    <div class="col-2">
      <i class="material-icons">lock</i>
    </div>
    <div class="col-8">
      <%= link_to channel&.channel_name, channel, id: "channel_#{channel.id}_#{@current_user&.id}", data: { channel_id: channel.id, user_id: @current_user&.id } %>
    </div>
    <% msg_count = channel.messages.where('created_at > ? AND user_id != ?', channel.last_read[current_user.id.to_s]&.to_time, current_user.id).count %>

    <%= turbo_stream_from "broadcast_#{channel.id}_#{current_user.id}" %>
    <div class="col-1">
      <%= render partial: 'partials/message_count', locals: { channel: channel, msg_count: } %>
    </div>
  </div>

<%end%>

app/views/channels/index.html.erb
<style>.dropdown-toggle::after{ display: none !important;  }</style>
<main>
	<div class="layout row">
		<!-- Start of Sidebar -->
		<div class="sidebar col-3 ml-5" id="sidebar">
			<div class="container">
				<div class="col-md-12">
					<div class="tab-content">

						<!-- Start of Discussions -->
						<div id="discussions" class="tab-pane fade active show">

              <!-- Start of user info -->
              <div class="discussions mb-4">
                <div class="row" style="margin-bottom: 2%;">
                  <div class="col-2 d-flex justify-content-center" >
                    <div class='avatar-md d-flex justify-content-center' style="background: #99ccff;color: white;" >
                      <% if current_user.profile_image.attached? %>
                        <%= image_tag url_for(current_user.profile_image), style: "width: 100%; height: 100%; object-fit: cover; border-radius: 100%" %>
                      <% else %>
                        <span style="font-size: 1.5em; padding: 0.2em">
                          <%= @current_user.username.upcase[0..1] %>
                        </span>
                      <% end %>
                    </div>  
                  </div>
                  <div class="col-7" style="top: 14px;">
                    <h5><%= @current_user.username %></h5>
                  </div>
                  <div class="col-3 dropdown" style="top: 6px;">
                    <button class="btn dropdown-toggle btn-primary" style="color: #808080;" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons">menu</i></button>
                    <div class="dropdown-menu bg-primary" aria-labelledby="dropdownMenuButton">

                      <%= link_to edit_user_path(@current_user.id), class: "btn power dropdown-item", remote: true do %>
                        <i class="material-icons">settings</i>
                        <span> Edit profile </span>
                      <% end %>

                      <%= button_to login_path(@current_user), method: :delete, class: "btn power dropdown-item", remote: true do %>
                        <i class="material-icons">power_settings_new</i>
                        <span> Logout </span>
                      <% end %>
                    </div>
                  </div>
                </div>                  
              </div>
              <!-- End of user info -->

              <!-- Start of Favourite channels -->
              <div class="discussions" style="margin-bottom: 7%;">
                <div class="row">
                  <div class="col-9">
                    <h5>FAVORITE CHANNELS</h5>
                    <div class="row">
                      <div class="col-2">
                        <i class="material-icons">person</i>
                      </div>
                      <div class="col-10">
                        <h6><%= button_to "#{@current_user.username}(you)", channels_path, method: :post, params: {is_private: true }, style: "background: none;border: none;color: grey;font-weight: bolder;" %></h6>
                      </div>
                    </div>
                  </div>
                </div> 
              </div>
              <!-- End of Favourite channels -->

              <!-- Start of private channels -->
              <div class="discussions">
                <div class="row">
                  <div class="col-9">
                    <h5>PRIVATE CHANNELS</h5>
                  </div>
                  <div class="col-3">
                    <button class="btn" style="color: #808080;" data-toggle="modal" data-target="#add_private_channel"><i class="material-icons">add</i></button>
                  </div>
                </div> 
                  <div class="list-group chats" role="tablist" id="channels">
                    <%= render @channels, locals: { current_user: @current_user }%> 
                  </div> 
              </div>

              <!-- End of private channels -->

              <!-- Start of direct messages -->
              <div class="discussions">
                <div class="row">
                  <div class="col-9">
                    <h5>DIRECT MESSAGES</h5>
                  </div>
                  <div class="col-3">
                    <button class="btn" style="color: #808080;" data-toggle="modal" data-target="#direct_message"><i class="material-icons">add</i></button>
                  </div>
                </div>
                <%= turbo_stream_from "direct_messages#{@current_user.id}" %>
                <div class="list-group chats" role="tablist" id="direct_messages_list">
                  <%= render partial: 'partials/direct_message', collection: @direct_messages, locals: { current_user: @current_user, user: @current_user } %>
                </div>                  
              </div>
              <!-- End of direct messages -->
						</div>
						<!-- End of Discussions -->
						<!-- Start of Settings -->
							<%= render 'partials/settings'%>
						<!-- End of Settings -->
					</div>
				</div>
			</div>
		</div>

    <%= turbo_stream_from "notification_#{@current_user.id}" do %>
      <%= render 'partials/notification'%>
    <%end%>   

    <%= turbo_stream_from "add_remove_channels_#{@current_user.id}" do %>
      <%= render 'partials/add_remove_channel'%>
    <%end%>      
		<!-- Start Show messages -->
			<%= render 'partials/show_messages' %>
		<!-- End Show messages -->

		<!-- End of Sidebar -->

		<!-- Start of Create Chat -->
			<%= render 'modals/create_channel' %>
			<%= render 'modals/group_members' %>
		<!-- End of Create Chat -->
	</div> <!-- Layout -->
</main>
<!-- core JavaScript -->
<script>
	function scrollToBottom(el) { el.scrollTop = el.scrollHeight; }
	scrollToBottom(document.getElementById('content'));
</script>