config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "logins#new"
  resources 'logins'
  resources 'users'
  post '/add_members' => 'users#add_members'
  delete '/remove_group_member' => 'channels#remove_group_member'
  resources 'channels' do
    resources 'messages'
  end

  get '/not_found' => 'errors#not_found'
end

app/controllers/logins_controller.rb
# frozen_string_literal: true

# Logins controller
class LoginsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email], password_digest: params[:user][:password_digest])
    if @user
      log_in(@user)
    else
      flash.now[:errors] = 'Please check your email and password!!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/views/logins/new.html.erb
<body class="start">
	<main>
		<% if flash.now[:errors].present? %>
			<div class = "row mt-2">
				<div class ="col-4"></div>				
				<div class ="col-4 p-4 text-white font-weight-bold" style="background: indianred;">
					<%= flash.now[:errors]%>
				</div>
				<div class ="col-4"></div>				
			</div>
		<% end %>
		<div class="layout">
			<!-- Start of Sign In -->
			<div class="main order-md-1">
				<div class="start">
					<div class="container">
						<div class="col-md-12">
							<div class="content">
								<h1>Sign in</h1>
                </br>
                <%= form_with model: @user, url: logins_path do |form| %>
									<div class="form-group">
										<%= form.text_field :email, id: "inputEmail", class: "form-control", placeholder: "Email Address", required: true %>
										<button class="btn icon"><i class="material-icons">mail_outline</i></button>
									</div>
									<div class="form-group">
                    <%= form.password_field :password_digest, id: 'inputPassword', class: "form-control",placeholder: 'Password', required: true %>
										<button class="btn icon"><i class="material-icons">lock_outline</i></button>
									</div>
									<%= form.submit "Sign In", class: "btn button" %>
									<div class="callout", style = 'display: block; margin-top: 4%;'>
										<span>Don't have account?<%= link_to 'Create Account', new_user_path %></span>
									</div>
                <% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Sign In -->
		</div> <!-- Layout -->
	</main>
</body>