config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "logins#new"
  resources 'logins'
  resources 'users'
  post '/add_members' => 'users#add_members'
  delete '/remove_group_member' => 'channels#remove_group_member'
  resources 'channels' do
    resources 'messages'
  end

  get '/not_found' => 'errors#not_found'
end

app/views/partials/_add_member.html.erb
<div class="row" style="display: flex;">
  <div class="col-10">
    <%= button_to user, channels_path(is_private: true, selected_user: [user]), method: :post, class: "list-group-item  list-group-item-action" %>
  </div>
  <div class="col-2">
    <%= button_to remove_group_member_path(member_id: member_id, channel_id: channel_id), style: 'background: none; border: none;', form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete do %>
      <i class="material-icons" style="color: red;">remove_circle</i>
    <% end %>
  </div>
</div>

app/views/partials/_add_remove_channel.html.erb
<div class="fixed-top d-flex justify-content-center" >
	<script>
		if(<%=remove%>)
		{
			if(window.location.href=='http://127.0.0.1:3000/channels/<%=channel_id%>')
			{
				window.location.replace('http://127.0.0.1:3000/channels/<%=personal_channel%>')
			}
			else{
				location.reload();
			}
		}
		else{
			location.reload();
		}
	</script>
</div>

app/views/partials/_direct_message.html.erb
<% unless current_user&.username == direct_message.channel_name%>
  <div class="row filterDiscussions all read single">
    <div class="col-2">
      <i class="material-icons">person</i>
    </div>
    <div class="col-8">
      <% if current_user.present? %>
        <% channel_name = (direct_message.channel_name.strip.split(",")).select {|a| a!=current_user.username}.join %>
      <% else %>
        <% channel_name = (direct_message.channel_name.strip.split(",")).select {|a| a == user.username}.join %>
      <% end %>
      <%= link_to channel_name, channel_path(id: direct_message.id, last_read_at: Time.now), id: "direct_message_#{direct_message.id}_#{@current_user&.id}", data: { channel_id: direct_message.id, user_id: @current_user&.id } %>
    </div>
    <% msg_count = direct_message.messages.where('created_at > ? AND user_id != ?', direct_message.last_read[user.id.to_s]&.to_time, user.id).count %>

    <%= turbo_stream_from "broadcast_#{direct_message.id}_#{user.id}" %>
    <div class="col-1">
      <%= render partial: 'partials/message_count', locals: { channel: direct_message, msg_count: , current_user: user } %>
    </div>
  </div>
<% end %>

app/views/partials/_members_count.html.erb
<button class="btn connect d-md-block d-none" name="1" data-toggle="modal" data-target="#showMembers"><i class="material-icons md-30">group</i><span><%=msg_count%></span></button>

app/views/partials/_message_count.html.erb
<%unless msg_count == 0%>
	<span class="badge badge-primary badge-pill" id="broadcast_<%=channel.id%>_<%=current_user.id%>"><%=msg_count%></span>
<%else%>
	<span id="broadcast_<%=channel.id%>_<%=current_user.id%>"></span>
<%end%>

app/views/partials/_messages_top.html.erb
<div class="top">
	<div class="container">
		<div class="col-md-12">
			<div class="inside">
				<div class="data">
					<h5>
						<a href="#">
							<% if @single_room.is_private %>
                <% unless @single_room.channel_name == current_user.username%>
  								<%= (@single_room.channel_name.strip.split(",")).select {|a| a!=current_user.username}.join %>
                <% else %>
                  <%= @single_room.channel_name%>
                <% end %>
							<% else %>
								<%= @single_room.channel_name%>
							<% end %>
						</a>
					</h5>
					<%# # <div class="row">
					#   <div class = "col-2">
					# 		<i class="material-icons online">fiber_manual_record</i>
					#   </div>
					#   <div class = "col-9">
					# 		<span>Active now</span>
					#   </div>
					# </div> %>
				</div>
        <% unless @single_room.is_private %>
          <div id="member_count">
	  				<%= render 'partials/members_count', msg_count: @single_room.member_ids.count %>
	  			</div>
					<!-- <div class="dropdown">
						<button class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons md-30">more_vert</i></button>
						<div class="dropdown-menu dropdown-menu-right">
							<button class="dropdown-item connect" name="1"><i class="material-icons">phone_in_talk</i>Voice Call</button>
							<button class="dropdown-item connect" name="1"><i class="material-icons">videocam</i>Video Call</button>
							<hr>
							<button class="dropdown-item"><i class="material-icons">clear</i>Clear History</button>
							<button class="dropdown-item"><i class="material-icons">block</i>Block Contact</button>
							<button class="dropdown-item"><i class="material-icons">delete</i>Delete Contact</button>
						</div>
					</div> -->
        <% end %>
			</div>
		</div>
	</div>
</div>

app/views/partials/_notification.html.erb
<div class="fixed-top d-flex justify-content-center" >
	<script>alert("New message")</script>
</div>

app/views/partials/_public_message_count.html.erb
<% if msg_count.present? %>
	<% unless msg_count.zero? %>
	<span id="msg_#{channel.id}" class="badge badge-primary badge-pill"><%=msg_count%></span>
	<% end %>
<% end %>

app/views/partials/_remove_channel.html.erb
<div class="fixed-top d-flex justify-content-center" >
	<script>
		if(<%=remove%>)
		{
			if(window.location.href=='http://127.0.0.1:3000/channels/<%=channel_id%>')
			{
				window.location.replace('http://127.0.0.1:3000/channels/<%=personal_channel%>')
			}
			else{
				location.reload();
			}
		}
		else{
			location.reload();
		}
	</script>
</div>

app/views/partials/_settings.html.erb
<div class="tab-pane fade" id="settings">			
	<div class="settings">
		<div class="categories" id="accordionSettings">
			<h1>Settings</h1>
			<!-- Start of My Account -->
			<div class="category">
				<a href="#" class="title collapsed" id="headingOne">
					<i class="material-icons md-30 online">person_outline</i>
					<div class="data">
						<h5>My Account</h5>
						<p>Update your profile details</p>
					</div>
				</a>
				<div class="collapse" style="display: block !important;">
					<div class="content">
						<div class="upload">
							<div class="data">
                <div class='avatar-xl' style="background: #99ccff;color: white;" ><span style="font-size: 30px;" class="p-2"><%= @current_user.username.upcase[0..1]%></span></div>
								<label>
									<input type="file">
									<span class="btn button">Upload avatar</span>
								</label>
							</div>
							<p>For best results, use an image at least 256px by 256px in either .jpg or .png format!</p>
						</div>
						<form>
							<div class="field">
								<label for="firstName">Username <span>*</span></label>
								<input type="text" class="form-control" id="firstName" placeholder="Username" value="Michael" required>
							</div>
							<div class="field">
								<label for="email">Email <span>*</span></label>
								<input type="email" class="form-control" id="email" placeholder="Enter your email address" value="michael@gmail.com" required>
							</div>
							<div class="field">
								<label for="password">Password</label>
								<input type="password" class="form-control" id="password" placeholder="Enter a new password" value="password" required>
							</div>
							<button type="submit" class="btn button w-100">Apply</button>
						</form>
					</div>
				</div>
			</div>
			<!-- End of My Account -->
			<!-- Start of Logout -->
			<div class="category">
				<%= button_to "sign_in", root_path, class: "title collapsed" %>
					<i class="material-icons md-30 online">power_settings_new</i>
					<div class="data">
						<h5>Power Off</h5>
						<p>Log out of your account</p>
					</div>
					<i class="material-icons">keyboard_arrow_right</i>
				</a>
			</div>
			<!-- End of Logout -->
		</div>
	</div>
</div>

app/views/partials/_show_messages.html.erb
<% if @single_room %>
  <%= turbo_stream_from @single_room %>
  <div class="main col-7">
  	<div class="tab-content" id="nav-tabContent">
  		<!-- Start of Babble -->
  		<div class="babble tab-pane fade active show" id="list-chat" role="tabpanel" aria-labelledby="list-chat-list">
  			<!-- Start of Chat -->
  			<div class="chat" id="chat1">
        <!-- Start of top bar of messages --> 
          <%= render 'partials/messages_top' %>        
        <!-- End of top bar of messages -->          
  				
  				<div class="content" id="content">
  					<div class="container">
  						<div class="col-md-12" id="messages">
						  <% @messages.each do |date, messages| %>
							<div class="date row">
								<div class="col-4">
									<hr>
								</div>
								<div class="col-4">
									<span><%= date == Date.today ? "Today" : date == Date.yesterday ? "Yesterday" : date.strftime("%B %d, %Y") %></span>
								</div>
								<div class="col-4">
									<hr>
								</div>

							</div>
							<%= render partial: 'messages/message', collection: messages %>
						  <% end %>
  						</div>
  					</div>
  				</div>
  				<div class="container">
  					<div class="col-md-12">
  						<div class="bottom">
                <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex position-relative w-100", id: 'message_send_form', :multipart => true) do |f| %>
                  <div class="row w-100">
                    <div class="col-10">
                      <%= f.text_area :content, id: 'chat-text', class: "form-control", autocomplete: 'off', placeholder: "Start typing for reply..." %>
                    </div>                    
                    <div class="col-1 p-0">
                      <%= f.button "", data: { disable_with: false }, class: "btn send" do %>
                        <i class="material-icons">send</i>
                      <% end %>
                    </div>
                    <div class="col-1 p-0">
        				<%= f.label :attachments do %>
                        <%= f.file_field :attachments, multiple: true %>
                        <span class="btn attach d-sm-block"><i class="material-icons">attach_file</i></span>
                      <% end %>
                    </div>
                  </div>
  							<% end %>
  						</div>
  					</div>
  				</div>
  			</div>
  			<!-- End of Chat -->
  		</div>
  	</div>
  </div>
<%end%>
<script>
  $(document).on('turbo:submit-end', function() {
    $('#message_send_form')[0].reset();
  });
</script>