config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "logins#new"
  resources 'logins'
  resources 'users'
  post '/add_members' => 'users#add_members'
  delete '/remove_group_member' => 'channels#remove_group_member'
  resources 'channels' do
    resources 'messages'
  end

  get '/not_found' => 'errors#not_found'
end

app/views/modals/_create_channel.html.erb
<div class="modal fade" id="add_private_channel" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="requests">
			<div class="title">
				<h1>New Channel</h1>
				<button type="button" class="btn closeModal" data-dismiss="modal" aria-label="Close"><i class="material-icons">close</i></button>
			</div>
			<div class="content">
				<%= form_with(remote: true, url: channels_path, class: "userForm" ) do |f| %>
					<div class="form-group">
						<label for="topic">Name:</label>
						<%= f.text_field :channel_name, class: "form-control", autocomplete: 'off', id: "topic", placeholder: "Enter the channel name..", required: true %>
					</div>
					<%= f.submit 'Create New Channel', data: { disable_with: false }, class: "btn button w-100" %>
				<%end%>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="direct_message" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="requests">
			<div class="title">
				<h1>Direct Message</h1>
				<button type="button" class="btn closeModal" data-dismiss="modal" aria-label="Close"><i class="material-icons">close</i></button>
			</div>
			<div class="content">
				<%= form_with(remote: true, url: channels_path, class: 'userForm' ) do |f| %>
				  <div class="form-group">
				  	<%= f.hidden_field :is_private, value: "true"%>
				    <%= text_field_tag :search, nil, placeholder: "Search users", class: "form-control searchMembers" %>
				  </div>
				  <div class="form-group" style="background: #f5f5f5; padding: 10px; max-height: 200px; overflow-y: auto;">
				    <% @users&.each do |user| %>
					      <div class="checkbox user-checkbox">
					        <%= radio_button_tag "selected_user[]", user.username, false, id: "user_#{user.id}" %>
					        <%= label_tag "user_#{user.id}", user.username, disabled: true %>
					      </div>
				    <% end %>
				  </div>
				  <div class="form-group">
				    <%= f.hidden_field :selected_users, class: "form-control  selectedMembers", readonly: true, placeholder: 'Selected member will be displayed here...', disabled: true %>
				  </div>
				  <%= f.submit 'Start chat', data: { disable_with: false }, class: "btn button w-100" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/modals/_group_members.html.erb
<!-- Modal to show members of the group -->
<div class="modal fade" id="showMembers" tabindex="-1" role="dialog" aria-hidden="true" style="margin-top: -17%; margin-left: 20%;">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="requests" style="border: 1px solid;">
			<div class="title" style="padding-bottom: 0 !important;">
				<h1>Show Members</h1>
        <button type="button" class="btn" data-dismiss="modal" aria-label="Add member" style="margin-left: 30%;" data-toggle="modal" data-target="#addMembers"><i class="material-icons">group_add</i></button>
				<button type="button" class="btn closeModal" data-dismiss="modal" aria-label="Close" ><i class="material-icons">close</i></button>
			</div>
			<div class="content list-group", id="add_member">
        <div class="row" style="display: flex;">
          <div class="col-10">
            <%= button_to "#{@current_user.username}(You)", channels_path(is_private: true), method: :post, class: "list-group-item  list-group-item-action" %>
          </div>
        </div>
        <% @single_room&.member_ids&.each do |member| %>
          <% next if member == @current_user.id %>
          <% username = User.find_by_id(member).username %>
          <%= render 'partials/add_member', user: username, member_id: member, channel_id: @single_room.id%>
        <% end %>
			</div>
		</div>
	</div>
</div>

<!-- Modal to add mebers to the group -->
<div class="modal fade" id="addMembers" tabindex="-1" role="dialog" aria-hidden="true" style="margin-top: -5%; margin-left: 20%;">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="requests">
      <div class="title">
        <h1>Add Members</h1>
        <button type="button" class="btn closeModal" data-dismiss="modal" aria-label="Close" ><i class="material-icons">close</i></button>
      </div>
      <div class="content">
        <%= form_with(remote: true, url: add_members_path, class: "userForm" ) do |f| %>
          <div class="form-group">
            <%= f.hidden_field :channel_id, value: "#{@single_room&.id}"%>
            <%= text_field_tag :search, nil, placeholder: "Search users", class: "form-control searchMembers" %>
          </div>
          <div class="form-group" style="background: #f5f5f5; padding: 10px; max-height: 200px; overflow-y: auto;">
            <%= f.text_field :users, class: "form-control", readonly: true, placeholder: 'Select the members if available:', disabled: true %>
            <% @users&.where&.not(id: @single_room&.member_ids)&.each do |user| %>
                <div class="checkbox user-checkbox">
                  <%= check_box_tag "selected_user[]", user.username, false, id: "user_#{user.id}" %>
                  <%= label_tag "user_#{user.id}", user.username, disabled: true %>
                </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.text_field :selected_users, class: "form-control selectedMembers", readonly: true, placeholder: 'Selected member will be displayed here...', disabled: true %>
          </div>
          <%= f.submit 'Add Member', data: { disable_with: false }, class: "btn button w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>